### ISSUE TITLE
Ajout de La Rochelle dans Vigilo

### ISSUE THREAD

**Issue by Tech-corolo** [jesuisundesdeux/vigilo-conf#12]
Bonjour,

Je suis Guillaume LAURIN, responsable technique chez COROLO (La Compagnie Rochelaise du Logiciel). Nous avons été sollicité par l'association Vive le Vélo de La Rochelle et Olivier Prentout (Adjoint à la mairie de La Rochelle) pour intégrer Vigilo pour La Rochelle et ses environs.

Nous avons d’ailleurs eu l'occasion d'assister à une présentation de Paul Leclercq le 4 novembre 2021 lors d'une réunion sur le sujet.

Depuis, nous avons intégré l'API Vigilo pour la ville de La Rochelle,

elle est configurée et disponible à cette adresse :  https://vigilo-lr.corolo.fr

Pouvez-vous l'ajouter et me dire qu'elles sont les démarches suivantes ?
Merci par avance,

Cordialement,
Guillaume

**Comment by qhess34** [comment]
Bonjour,

Pouvez-vous m'envoyer le nom de la zone à afficher dans les applications
ainsi que le nom du scope configuré sous le format XX_nomzone ?

Ces informations me permettront d'ajouter votre instances aux applications

Cordialement,

Quentin HESS

**Comment by oprentout** [comment]
Bonsoir Quentin,

En faisant le paramétrage, nous avons indiqué comme nom de scope 17_larochelle.
Pour le nom de zone, tout simplement "La Rochelle".

Bien cordialement,

Olivier PRENTOUT

**Comment by qhess34** [comment]
Bonjour,

Je viens d'ajouter votre instance
Vous pouvez rejoindre notre Slack pour échanger sur le suivi et échanges Vigilo https://join.slack.com/t/jesuisundesdeux/shared_invite/zt-fxp7ksrn-_HX5hBwvJEkDnZgof9Ff6g

Cordialement,
