### ISSUE TITLE
Ajout de l'Agglomération Le Cotentin dans Vigilo

### ISSUE THREAD

**Issue by nicolasVr** [jesuisundesdeux/vigilo-conf#16]
Bonjour,

Je suis Nicolas Vivier, co-Président de Vélorution Cherbourg. Nous avons découvert Vigilo qui fait ce que nous avions envie de faire :-)
Nous avons fait l'installation et la configuration sur https://vigilo.velorution-cherbourg.fr
Le nom du scope est 50_cotentin et le nom de la zone est Agglomération Le Cotentin.
Pouvez-vous ajouter notre instance et m'indiquer s'il y a d'autres actions à mener ?
Au cours de l'installation, j'ai trouvé qqs erreurs dans la doc, en particulier sur Twitter car la procédure a dû changer depuis la rédaction. J'essaierai de proposer des mises à jour.
J'ai aussi des questions sur Umap, mais je pense que ce n'est pas le lieu.
Merci d'avance pour l'ajout en tous cas.
Cordialement

**Comment by qhess34** [comment]
Bonjour,

Je viens de procéder à l'ajout de votre instance (https://github.com/jesuisundesdeux/vigilo-conf/commit/f8b1ded2c950a45aa56c2937e94d79caa49c640f).
Vous pouvez nous rejoindre sur Slack via https://join.slack.com/t/jesuisundesdeux/shared_invite/zt-1m5fpnx6d-mJHsyPKyKLbT836uAfBZ7g afin de faciliter les échanges futurs.

Si besoin de contribuer sur la doc (présente sur vigilo.city) vous pouvez le faire via le repo https://github.com/jesuisundesdeux/vigilo-website

Cordialement,

Quentin
