### ISSUE TITLE
Ajout de la ville "Lorient Agglomération"

### ISSUE THREAD

**Issue by florentulve** [jesuisundesdeux/vigilo-conf#17]
Bonjour,

Je représente l'association claav/syklet de Lorient et son aggomération.

Nous avons fait l'installation et la configuration d'un backend vigilo sur https://vigilo.claav.fr/

Le nom du scope est 56_lorient et le nom de la zone est Lorient Agglomération.

Pouvez-vous ajouter notre instance et m'indiquer s'il y a d'autres actions à mener ?

Merci à vous.
Cordialement.

**Comment by qhess34** [comment]
Bonjour,

Je viens de procéder à l'ajout de votre instance (https://github.com/jesuisundesdeux/vigilo-conf/commit/6e3843bf4a36e8c971d9224ccb1056374380590c).
Vous pouvez nous rejoindre sur Slack via https://join.slack.com/t/jesuisundesdeux/shared_invite/zt-1m5fpnx6d-mJHsyPKyKLbT836uAfBZ7g afin de faciliter les échanges futurs.

Cordialement,

Quentin
