### ISSUE TITLE
Instance de test pour la ville d'Annemasse

### ISSUE THREAD

**Issue by wizmer** [jesuisundesdeux/vigilo-conf#18]
Bonjour,

Je represente l'association En Ville A Velo d'Ambilly et j'aimerai avoir a une instance de démonstration afin de reflechir a la mise en place d'une reelle instance si l'experience est concluante. Comment dois-je m'y prendre ?

Merci !

**Comment by qhess34** [comment]
Bonjour,

Voici la procédure https://vigilo.city/fr/villes/maville/

Cordialement,

**Comment by wizmer** [comment]
C'est bien la procedure que j'ai suivi et c'est pour cette raison que je vous ai contacte.

```
Démonstration

Il est possible, dans la limite de 5 testeurs maximum de bénéficier d’une instance de test pour votre zone géographique.

Pour celà, n’hesitez pas à nous contacter...
```
Si ce n'est pas vous, qui dois-je contacter ?
Merci

**Comment by qhess34** [comment]
Bonjour,

C'est bien moi.
Comme indiqué dans la procédure pouvez vous me transmettre les informations
suivantes :

   - Nom de la zone géographique
   - Limites géographique en degrés décimales (latitude min/max, longitude
   min/max)
   - Adresse mail de contact

Bonne journée

Quentin

**Comment by wizmer** [comment]
Ah ok, super. Merci de votre reponse.

- Nom de la zone géographique: Annemasse Agglo
- lat: 46.159957 -> 46.214763
- lon: 6.190250 -> 6.286883 
- adresse de contact: benoit.coste@pm.me
- compte play store de test: ben.coste@gmail.com

Bonne journée

**Comment by qhess34** [comment]
Bonjour,

L'instance de test a été ajoutée, vous pouvez installé l'appli permettant
d'y accéder avec ce lien :
https://play.google.com/store/apps/details?id=com.velocite34.vigilo
(désinstaller Vigilo avant) ou en web via https://app.vigilo.city/?beta

Vous pouvez rejoindre notre slack pour échanger via le lien
https://join.slack.com/t/jesuisundesdeux/shared_invite/zt-1o7c1796u-Gez7mOFKwc64faukjYodVQ


Cordialement,

Quentin
