### ISSUE TITLE
Ajout de "Saint Lo Agglo"

### ISSUE THREAD

**Issue by assovelo** [jesuisundesdeux/vigilo-conf#19]
Bonjour,

Je fais partie de l'association Asso V'lo sur Saint-Lô et son aggomération (50, Manche).
Nous avons fait la configuration d'un backend vigilo sur vigilio.assovelo.fr
Le nom du scope est 50_saintloagglo et le nom de la zone est Saint-Lo Agglo
Pourriez-vous ajouter notre instance et m'indiquer s'il y a d'autres actions à mener ?
Merci beaucopup !
- Eric

**Comment by qhess34** [comment]
Bonjour,

C'est ajouté
https://github.com/jesuisundesdeux/vigilo-conf/commit/e6dbc266c51605621807cb5cd4b6d0c59fbbf05a

Cordialement,
