### ISSUE TITLE
Ajout de Quimper

### ISSUE THREAD

**Issue by batchennings** [jesuisundesdeux/vigilo-conf#20]
Bonjour,

Je m'occupe des outils informatiques à Kernavélo, à Quimper, et je viens d'installer une instance de Vigilo backend sur `vigilo.kernavelo.org`.
Pourriez-vous ajouter notre instance ?

Merci d'avance,
Thomas

**Comment by batchennings** [comment]
L'identifiant du scope est `quimper_communaute`. Le département : `29`.

**Comment by qhess34** [comment]
Bonjour,

Le scope doit être sous le format XX_yyyy où XX est le numéro du
département et yyyy un nom court correspondant à la zone.
Pouvez-vous me donner aussi le nom à afficher sur la liste des instances?

Quentin

**Comment by batchennings** [comment]
Merci ! Je viens de modifier les infos sur l'instance. L'identifiant du scope est donc maintenant `29_quimper`. Le nom à afficher est `Quimper Communauté`.

**Comment by qhess34** [comment]
Bonjour,

C'est ajouté =>
https://github.com/jesuisundesdeux/vigilo-conf/commit/e70b0db93796ed07fcd7eb1c699143127e688ce1

Cordialement,

Quentin
