### ISSUE TITLE
Instance de demonstration

### ISSUE THREAD

**Issue by oertz** [jesuisundesdeux/vigilo-conf#21]
Beau projet, bravo ! Nous, antenne Pays d'Evian de l'[Association Mobilité Douce Chablais (AMDC)](https://www.mobilitedoucechablais.fr/antenne-pays-d-evian) envisageons donc un déploiement Vigilo sur notre territoire.
 
Les conditions semblent remplies pour ajouter Evian-les-Bains pour tester :
- [x] Nous sommes une association reconnue pour son engagement auprès de la municipalité d'Evian-les-Bains sur l'élaboration du plan mobilité douce, mais aussi auprès de l'Agglomération Thonon sur son schéma directeur cyclable
- [X] Nous avons la capacité de maintenir l’application sur le périmètre de la zone voulue en toute autonomie (un ingénieur informatique dans l'équipe), aussi d'en assurer le suivi des mises à jour et le bon fonctionnement avec un plan prévu pour assurer sa pérenité (documentation, sauvegarde, …)
- [X] Une petite équipe de 3-5 personnes se déclare prête à valider les observations et réaliser le floutage des éléments
- [X] La zone, non-couverte par Vigilo, est pour le moment restreinte à la ville d'Evian-les-Bains qui représente la plus grande ville de l'antenne Pays d'Evian

Pour finaliser la mise en place de ce projet Vigilo pour Evian-les-Bains et notamment confirmer que le fonctionnement de Vigilo correspond bien à nos besoins (ce qui semble être le cas), nous demandons une instance de demonstration avec les informations suivantes :

- Nom de la zone géographique : Evian-les-Bains
- Limites géographique en degrés décimales :
  latitude min/max 46.3788910999999970/46.4033599999999993
  longitude min/max 6.5679547999999999/6.6141700999999999
- Adresse mail de contact : amdc.evian@modouce.fr
- Liste des compte playstore des testeurs : un test par l'application web pourrait être suffisant
- L'instance déployée et configurée semble-t-il avec succès sur un hébergement Nuxit Web : www.modouce.fr/vigilo/

D'avance merci.
Pour les membres de l'antenne Pays d'Evian de l'AMDC.

**Comment by qhess34** [comment]
Bonjour,

Je vois que vous avez installé une instance, c'est celle que vous voulez
utiliser en démo ?
Si oui, pouvez vous me fournir le scope que vous avez configuré dessus
(sous la forme XX_YYY ou XX est le numéro du département et YYY le nom
court de la zone ?)

Cordialement,

Quentin

**Comment by oertz** [comment]
Bonjour,
merci pour votre réponse. 

Oui, https://www.modouce.fr/vigilo/ est l'instance que nous souhaiterions tester. J'avais peut-être mal compris que vous proposiez une instance de test en soi, mais l'installation s'est finalement bien déroulée (quoique nous verrons bien à l'utilisation si tout est bien configuré, ex. mapquest).

L'identifiant de scope configuré est le suivant : 74_Evian

J'ai lu qu'un slack serait mis à disposition. Le cas échéant nous sommes preneur pour les détails.

D'avance merci.
Pour les membres de l'antenne Pays d'Evian de l'AMDC.

**Comment by qhess34** [comment]
Bonjour,

Je viens d'ajouter la zone Evian =>
https://github.com/jesuisundesdeux/vigilo-conf/commit/fdf3f4a1aad72e32e30142c16a4f86f7b00be763
Vous pouvez rejoindre le slack via
https://join.slack.com/t/jesuisundesdeux/shared_invite/zt-1ydpvyhjk-cw34QJhYnOQC0yJns5d3eQ
(rejoindre ensuite les canaux #vigilo*)

Cordialement,

Quentin

**Comment by oertz** [comment]
Merci pour la réactivité ! 

Un test rapide semble montrer que ça fonctionne. Resterait à configurer un compte Twitter. Nous allons tester cela dans tous les sens au sein du groupe de pilotage de notre association, tant la version webapp que mobile. Suite au prochain épisode.

Olivier.
Pour les membres de l'antenne Pays d'Evian de l'AMDC.
