### ISSUE TITLE
Mise en place Vigilo  par Nice-à-Vélo

### ISSUE THREAD

**Issue by DanieleSottile** [jesuisundesdeux/vigilo-conf#22]
Bonjour,

Je vois qu'il faut créer une nouveau ticket ici pour que notre territoire soit ajouté a Vigilo.

Je fais partie de l'association Nice-à-Vélo et en train de mettre en place l'appli.

Je n'ai pas trouvé plus de détails sur le type d'information á renseigner.

Cordialement,
Daniele Sottile

**Comment by qhess34** [comment]
Bonjour,
Il vous faut fournir :
* URL de l'instance (https)
* Scope configuré : XX_ville
Exemples: https://github.com/jesuisundesdeux/vigilo-conf/blob/main/main/citylist.json

**Comment by DanieleSottile** [comment]
Bonjour !

Ca y est, j'ai les info:

"Métropole Nice Côte d'Azur":{
      "api_path":"https://vigiloniceavelo.fr",
      "country":"France",
      "prod":true,
      "scope":"06_METROPOLENCA"
}

**Comment by DanieleSottile** [comment]
J'ai crée un nouveau ticket.
