### ISSUE TITLE
Ajout ville de Libourne à Vigilo

### ISSUE THREAD

**Issue by Klodd** [jesuisundesdeux/vigilo-conf#23]
Bonjour, je vous écris pour vous demander l'ajout d'une ville à Vigilo.

L'association en charge de l'instance est Libournavélo (libournavelo.fr)

Adresse du backend : florgz.com/vigilo/
Nom du scope : Libournais
Identifiant : 33_libournais

Scope le plus proche existant : Bordeaux Métropole. J'ai vérifié que mon scope ne recouvre pas ce scope.

Je ne pense pas que cela ait beaucoup d'importance mais éventuellement je pourrai migrer le backend sur vigilo.libournavelo.fr Dites moi si c'est essentiel ou non

Merci pour votre aide

**Comment by qhess34** [comment]
Scope ajouté
