### ISSUE TITLE
Ajout de Métropole Nice Cote d'Azur à Vigilo

### ISSUE THREAD

**Issue by DanieleSottile** [jesuisundesdeux/vigilo-conf#24]
Bonjour,

Mon premier ticket étant assez ancien, j'ai ouvert un nouveau pour que ça soit plus clair.
L'instance sera gérée par les bénévoles de l'association Nice à Vélo niceavelo.org

Voilà les informations delandées :

"Métropole Nice Côte d'Azur":{
"api_path":"https://vigiloniceavelo.fr/",
"country":"France",
"prod":true,
"scope":"06_METROPOLENCA"
}

Cordialement,
Daniele

**Comment by qhess34** [comment]
c'est ajouté :)
