### ISSUE TITLE
Instance de demonstration

### ISSUE THREAD

**Issue by MaximeR2001** [jesuisundesdeux/vigilo-conf#25]
Lozère

Limites : 
- sud : 44,10283 N ; 3,54895 E
- nord : 44,97909 N ; 3,37520 E
- est : 44,45366 N ; 3,99896 E
- ouest : 44,65501 N ; 2,97853 E

maxime@mobilite-lozere.fr

Testeurs

remy.cassabel@gmail.com
camilloutiteaigue@gmail.com

**Comment by MaximeR2001** [comment]
Bonjour je suis au bon endroit pour créer une instance de test ?

**Comment by qhess34** [comment]
Je viens d'ajouter l'instance en mode test.

Pour y avoir accès, rendez-vous sur :
- Pour l'appli android (la désinstaller avant si déjà installée) : https://play.google.com/apps/testing/com.velocite34.vigilo 
- Pour la version web : https://app.vigilo.city/?beta
- 
Désolé pour le temps d'attente
