### ISSUE TITLE
Instance de demonstration Colmar

### ISSUE THREAD

**Issue by Martoni** [jesuisundesdeux/vigilo-conf#26]
Bonjour,

L'association[ CADRes Colmar et environs](https://www.cadrescolmar.org/) souhaite mettre en place le système vigilo pour l'agglomération.

Les limites de l'agglomération sont définies par les quatre points suivants:

```
 7.201195,48.064773
 7.391224,47.98636
 7.511559,48.127601
 7.357407,48.134934
```

Représenté sur la [carte framasoft suivante](https://framacarte.org/en/map/zone-vigilo_189560).

Je ne sais pas comment marche la définition des limites de la zone, mais à terme il serait préférable d'utiliser les limites des communes pour mieux inclure toute la zone.

Mail de contact association : contact@cadrescolmar.org

Compte de testeuses et testeurs:

- lepingouin.tux@gmail.com
- eloi.desseigne@gmail.com
- hamnet68@gmail.com

**Comment by Martoni** [comment]
Bonjour,

Pensez vous que nous puissions avoir une «instance» de démonstration avant de chercher à l'installer sur notre serveur ?

Merci
FabienM pour le CADRes colmar et environ

**Comment by qhess34** [comment]
Bonjour,

Je vais m'en occuper

Quentin

**Comment by qhess34** [comment]
Je viens d'ajouter l'instance en mode test.

Pour y avoir accès, rendez-vous sur :

Pour l'appli android (la désinstaller avant si déjà installée) : https://play.google.com/apps/testing/com.velocite34.vigilo
Pour la version web : https://app.vigilo.city/?beta
Désolé pour le temps d'attente

**Comment by Martoni** [comment]
Super merci !
On test tout ça et on verra pour installer l'instance sur nos serveurs ensuite.
Fabien M
CADRes Colmar

**Comment by Martoni** [comment]
Du coup j'ai une question pour @qhess34 
Est-ce possible d'être administrateur de cette instance beta ?
Et comment devient on modérateur, surtout si on ne peut pas être administrateur ?
Merci

**Comment by qhess34** [comment]
Bonjour Fabien,

L'instance de demo ne permet pas d'accès administrateur. Je peux en
revanche ajouter des modérateurs, il faut qu'ils génèrent leur clé et me
les donnent.

Quentin

**Comment by Martoni** [comment]
Ok, Par contre je ne sais pas trop comment envoyer un message privé du coup voici mon mail pour que je puisse envoyer la clef en retour : mail@fabienm.eu

**Comment by qhess34** [comment]
Tu peux rejoindre notre slack via
https://join.slack.com/t/jesuisundesdeux/shared_invite/zt-2k30yze11-QIY8SBd7zQi3wizRXBpz9w
sinon
